In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\sneha\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sneha\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sneha\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sneha\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sneha\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sneha\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [7]:
# From a list
ages = pd.Series([21, 19, 22, 20])
#print(ages)
# With custom index
ages = pd.Series([21, 19, 22,20], index=["Alex", "Maria", "John", "Sara"])
print(ages)

Alex     21
Maria    19
John     22
Sara     20
dtype: int64

In [6]:
# From a dictionary
data = {
    "name": ["Alex", "Maria", "John", "Sarah"],
    "age": [25, 19, 22, 45],
    "score": [85, 78, 90.5, 78]
}
#print(data)
df = pd.DataFrame(data)
print(df)

    name  age  score
0   Alex   25   85.0
1  Maria   19   78.0
2   John   22   90.5
3  Sarah   45   78.0

In [11]:
#import pandas as pd
df = pd.read_csv("students.csv")
print(df)

   id   name  age  score
0   1   Alex   21     85
1   2  Maria   19     78
2   3   John   22     90
3   4   Sara   20     88
4   5  David   18     72

In [13]:
df[["name", "age"]]

    name  age
0   Alex   21
1  Maria   19
2   John   22
3   Sara   20
4  David   18

In [25]:
df[(df["age"] >= 20) & (df["score"]>60)]

   id  name  age  score
0   1  Alex   21     85
2   3  John   22     90
3   4  Sara   20     88

In [20]:
df.iloc[2:,1:3]

    name  age
2   John   22
3   Sara   20
4  David   18

In [22]:
df.loc[df["age"] >= 20, ["name","age"]]

   name  age
0  Alex   21
2  John   22
3  Sara   20

In [24]:
df[df["age"] >= 20][["name", "age"]]

   name  age
0  Alex   21
2  John   22
3  Sara   20

In [27]:
import pandas as pd
data = {
    "Name": ["Alex", "Riya", "John", "Tony", "Sam"],
    "Department": ["HR", "IT", "IT", "HR", "IT"],
    "Salary": [30000, 50000, 45000, 32000, 52000]
}
df = pd.DataFrame(data)
print(df)
df.groupby("Department")["Salary"].mean()

   Name Department  Salary
0  Alex         HR   30000
1  Riya         IT   50000
2  John         IT   45000
3  Tony         HR   32000
4   Sam         IT   52000

Department
HR    31000.0
IT    49000.0
Name: Salary, dtype: float64

In [28]:
df.groupby("Department")["Salary"].mean().sort_values(ascending=False)

Department
IT    49000.0
HR    31000.0
Name: Salary, dtype: float64

In [29]:
df.groupby("Department")["Salary"].mean().sort_values(ascending=False)

Department
IT    49000.0
HR    31000.0
Name: Salary, dtype: float64

In [98]:
#Practice Questions
#Data Understanding
#Load the dataset into a DataFrame called df. 
df = pd.read_csv("nba.csv")

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0
(458, 9)
Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB
None

In [100]:
#Display the first 5 rows. 
print(df.head(5))

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0

In [102]:
df = df.dropna(how="all") #drops rows which are completely empty
#Check the number of rows and columns. 
print(df.shape)

(457, 9)

In [99]:
#List all column names. 
print(df.columns)

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [103]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 457 entries, 0 to 456
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 35.7+ KB
None

In [56]:
#Data Cleaning 
#Convert the Salary column to numeric (handle errors). 
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")
df["Salary"]

0      7730337.0
1      6796117.0
2            NaN
3      1148640.0
4      5000000.0
         ...
452    2239800.0
453    2433333.0
454     900000.0
455    2900000.0
456     947276.0
Name: Salary, Length: 457, dtype: float64

In [57]:
#Count how many missing (NaN) values are in each column
print(df.isna().sum())

Name         0
Team         0
Number       0
Position     0
Age          0
Height       0
Weight       0
College     84
Salary      11
dtype: int64

In [58]:
#Drop rows where Salary is missing. 
df = df.dropna(subset = ["Salary"])

In [65]:
#Fill missing College values with "Unknown". 
df = df.fillna({"College": "Unknown"})

In [67]:
#Filtering Data
#Show all players from Boston Celtics. 
boston_players = df[df["Team"] == "Boston Celtics"]
print(boston_players)

               Name            Team  Number Position   Age Height  Weight  \
0     Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1       Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
3       R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4     Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
5      Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
6     Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0
7      Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0
8      Terry Rozier  Boston Celtics    12.0       PG  22.0    6-2   190.0
9      Marcus Smart  Boston Celtics    36.0       PG  22.0    6-4   220.0
10  Jared Sullinger  Boston Celtics     7.0        C  24.0    6-9   260.0
11    Isaiah Thomas  Boston Celtics     4.0       PG  27.0    5-9   185.0
12      Evan Turner  Boston Celtics    11.0       SG  27.0    6-7   220.0
13      James Young  Boston Celtics    13.0       SG  20.0    6-6   215.0
14     Tyler Zeller  Boston Celtics    44.0        C  26.0    7-0   253.0

           College      Salary
0            Texas   7730337.0
1        Marquette   6796117.0
3    Georgia State   1148640.0
4          Unknown   5000000.0
5          Unknown  12000000.0
6              LSU   1170960.0
7          Gonzaga   2165160.0
8       Louisville   1824360.0
9   Oklahoma State   3431040.0
10      Ohio State   2569260.0
11      Washington   6912869.0
12      Ohio State   3425510.0
13        Kentucky   1749840.0
14  North Carolina   2616975.0

In [70]:
#Show players whose Age is greater than 30. 
players_above_30 = df[df["Age"] >30]
print(players_above_30)

                Name                    Team  Number Position   Age Height  \
19      Jarrett Jack           Brooklyn Nets     2.0       PG  32.0    6-3
31      Lou Amundson         New York Knicks    17.0       PF  33.0    6-9
33   Carmelo Anthony         New York Knicks     7.0       SF  32.0    6-8
34     Jose Calderon         New York Knicks     3.0       PG  34.0    6-3
43     Sasha Vujacic         New York Knicks    18.0       SG  32.0    6-7
..               ...                     ...     ...      ...   ...    ...
406  Tayshaun Prince  Minnesota Timberwolves    12.0       SF  36.0    6-9
413    Nick Collison   Oklahoma City Thunder     4.0       PF  35.0   6-10
415       Randy Foye   Oklahoma City Thunder     6.0       SG  32.0    6-4
420    Nazr Mohammed   Oklahoma City Thunder    13.0        C  38.0   6-10
434      Chris Kaman  Portland Trail Blazers    35.0        C  34.0    7-0

     Weight           College      Salary
19    200.0      Georgia Tech   6300000.0
31    220.0              UNLV   1635476.0
33    240.0          Syracuse  22875000.0
34    200.0           Unknown   7402812.0
43    195.0           Unknown    947276.0
..      ...               ...         ...
406   212.0          Kentucky    947276.0
413   255.0            Kansas   3750000.0
415   213.0         Villanova   3135000.0
420   250.0          Kentucky    222888.0
434   265.0  Central Michigan   5016000.0

[89 rows x 9 columns]

In [72]:
#Filter players who play as PG (Point Guard)
players_pos_as_PG = df[df["Position"] == "PG"]
print(players_pos_as_PG)

              Name                    Team  Number Position   Age Height  \
0    Avery Bradley          Boston Celtics     0.0       PG  25.0    6-2
8     Terry Rozier          Boston Celtics    12.0       PG  22.0    6-2
9     Marcus Smart          Boston Celtics    36.0       PG  22.0    6-4
11   Isaiah Thomas          Boston Celtics     4.0       PG  27.0    5-9
19    Jarrett Jack           Brooklyn Nets     2.0       PG  32.0    6-3
..             ...                     ...     ...      ...   ...    ...
440  Brian Roberts  Portland Trail Blazers     2.0       PG  30.0    6-1
443     Trey Burke               Utah Jazz     3.0       PG  23.0    6-1
445     Dante Exum               Utah Jazz    11.0       PG  20.0    6-6
453   Shelvin Mack               Utah Jazz     8.0       PG  26.0    6-3
454      Raul Neto               Utah Jazz    25.0       PG  24.0    6-1

     Weight         College     Salary
0     180.0           Texas  7730337.0
8     190.0      Louisville  1824360.0
9     220.0  Oklahoma State  3431040.0
11    185.0      Washington  6912869.0
19    200.0    Georgia Tech  6300000.0
..      ...             ...        ...
440   173.0          Dayton  2854940.0
443   191.0        Michigan  2658240.0
445   190.0         Unknown  3777720.0
453   203.0          Butler  2433333.0
454   179.0         Unknown   900000.0

[88 rows x 9 columns]

In [74]:
#Find players with Salary greater than 5,000,000.
salary_above_5M = df[df["Salary"] > 5000000]
print(f"salary_above_5: {salary_above_5M}")

                 Name                    Team  Number Position   Age Height  \
0       Avery Bradley          Boston Celtics     0.0       PG  25.0    6-2
1         Jae Crowder          Boston Celtics    99.0       SF  25.0    6-6
5        Amir Johnson          Boston Celtics    90.0       PF  29.0    6-9
11      Isaiah Thomas          Boston Celtics     4.0       PG  27.0    5-9
19       Jarrett Jack           Brooklyn Nets     2.0       PG  32.0    6-3
..                ...                     ...     ...      ...   ...    ...
433  Gerald Henderson  Portland Trail Blazers     9.0       SG  28.0    6-5
434       Chris Kaman  Portland Trail Blazers    35.0        C  34.0    7-0
444        Alec Burks               Utah Jazz    10.0       SG  24.0    6-6
446    Derrick Favors               Utah Jazz    15.0       PF  24.0   6-10
448    Gordon Hayward               Utah Jazz    20.0       SF  26.0    6-8

     Weight           College      Salary
0     180.0             Texas   7730337.0
1     235.0         Marquette   6796117.0
5     240.0           Unknown  12000000.0
11    185.0        Washington   6912869.0
19    200.0      Georgia Tech   6300000.0
..      ...               ...         ...
433   215.0              Duke   6000000.0
434   265.0  Central Michigan   5016000.0
444   214.0          Colorado   9463484.0
446   265.0      Georgia Tech  12000000.0
448   226.0            Butler  15409570.0

[144 rows x 9 columns]

In [76]:
# Sorting
#Sort players by Salary (highest first). 
salary_sorted = df.sort_values(by = "Salary", ascending = False)
print(f"salary_sorted: {salary_sorted}")

                       Name                  Team  Number Position   Age  \
109             Kobe Bryant    Los Angeles Lakers    24.0       SF  37.0
169            LeBron James   Cleveland Cavaliers    23.0       SF  31.0
33          Carmelo Anthony       New York Knicks     7.0       SF  32.0
251           Dwight Howard       Houston Rockets    12.0        C  30.0
339              Chris Bosh            Miami Heat     1.0       PF  32.0
..                      ...                   ...     ...      ...   ...
175            Jordan McRae   Cleveland Cavaliers    12.0       SG  25.0
135           Alan Williams          Phoenix Suns    15.0        C  23.0
291         Orlando Johnson  New Orleans Pelicans     0.0       SG  27.0
130            Phil Pressey          Phoenix Suns    25.0       PG  25.0
32   Thanasis Antetokounmpo       New York Knicks    43.0       SF  23.0

    Height  Weight           College      Salary
109    6-6   212.0           Unknown  25000000.0
169    6-8   250.0           Unknown  22970500.0
33     6-8   240.0          Syracuse  22875000.0
251   6-11   265.0           Unknown  22359364.0
339   6-11   235.0      Georgia Tech  22192730.0
..     ...     ...               ...         ...
175    6-5   179.0         Tennessee    111196.0
135    6-8   260.0  UC Santa Barbara     83397.0
291    6-5   220.0  UC Santa Barbara     55722.0
130   5-11   175.0          Missouri     55722.0
32     6-7   205.0           Unknown     30888.0

[446 rows x 9 columns]

In [77]:
#Sort players by Age (youngest first). 
sort_age = df.sort_values(by= "Age")
print(f"sorted_age: {sort_age}")

                Name                    Team  Number Position   Age Height  \
122     Devin Booker            Phoenix Suns     1.0       SG  19.0    6-6
226    Rashad Vaughn         Milwaukee Bucks    20.0       SG  19.0    6-6
192  Stanley Johnson         Detroit Pistons     3.0       SF  20.0    6-7
393  Emmanuel Mudiay          Denver Nuggets     0.0       PG  20.0    6-5
56     Jahlil Okafor      Philadelphia 76ers     8.0        C  20.0   6-11
..               ...                     ...     ...      ...   ...    ...
261     Vince Carter       Memphis Grizzlies    15.0       SG  39.0    6-6
102   Pablo Prigioni    Los Angeles Clippers     9.0       PG  39.0    6-3
304     Andre Miller       San Antonio Spurs    24.0       PG  40.0    6-3
298       Tim Duncan       San Antonio Spurs    21.0        C  40.0   6-11
400    Kevin Garnett  Minnesota Timberwolves    21.0       PF  40.0   6-11

     Weight         College     Salary
122   206.0        Kentucky  2127840.0
226   202.0            UNLV  1733040.0
192   245.0         Arizona  2841960.0
393   200.0         Unknown  3102240.0
56    275.0            Duke  4582680.0
..      ...             ...        ...
261   220.0  North Carolina  4088019.0
102   185.0         Unknown   947726.0
304   200.0            Utah   250750.0
298   250.0     Wake Forest  5250000.0
400   240.0         Unknown  8500000.0

[446 rows x 9 columns]

In [79]:
#Find the average salary per team.
avg_salary_per_team = df.groupby("Team")["Salary"].mean().round(2)
print(f"avg_salary_per_team: {avg_salary_per_team}")

Team
Atlanta Hawks             4860196.67
Boston Celtics            4181504.86
Brooklyn Nets             3501898.33
Charlotte Hornets         5222728.00
Chicago Bulls             5785558.53
Cleveland Cavaliers       7642049.21
Dallas Mavericks          4746582.13
Denver Nuggets            4294423.57
Detroit Pistons           4477884.20
Golden State Warriors     5924599.80
Houston Rockets           5018868.07
Indiana Pacers            4450121.73
Los Angeles Clippers      6323642.67
Los Angeles Lakers        4784695.40
Memphis Grizzlies         5467920.00
Miami Heat                6347359.46
Milwaukee Bucks           4350219.81
Minnesota Timberwolves    4593053.62
New Orleans Pelicans      4355303.89
New York Knicks           4581493.62
Oklahoma City Thunder     6251019.87
Orlando Magic             4297247.86
Philadelphia 76ers        2213778.14
Phoenix Suns              4229675.67
Portland Trail Blazers    3220121.20
Sacramento Kings          4778911.07
San Antonio Spurs         5629515.53
Toronto Raptors           4741174.07
Utah Jazz                 4204006.07
Washington Wizards        5088575.73
Name: Salary, dtype: float64

In [84]:
#Count number of players in each team. 
count_per_team = df.groupby("Team").size()
print(f"count_per_team: {count_per_team}")

Team
Atlanta Hawks             15
Boston Celtics            14
Brooklyn Nets             15
Charlotte Hornets         15
Chicago Bulls             15
Cleveland Cavaliers       14
Dallas Mavericks          15
Denver Nuggets            14
Detroit Pistons           15
Golden State Warriors     15
Houston Rockets           15
Indiana Pacers            15
Los Angeles Clippers      15
Los Angeles Lakers        15
Memphis Grizzlies         14
Miami Heat                13
Milwaukee Bucks           16
Minnesota Timberwolves    13
New Orleans Pelicans      19
New York Knicks           16
Oklahoma City Thunder     15
Orlando Magic             14
Philadelphia 76ers        14
Phoenix Suns              15
Portland Trail Blazers    15
Sacramento Kings          15
San Antonio Spurs         15
Toronto Raptors           15
Utah Jazz                 15
Washington Wizards        15
dtype: int64

In [85]:
#Find the maximum salary in each team. 
max_salary_per_team = df.groupby("Team")["Salary"].max() 
print(f"max_salary_per_team: {max_salary_per_team}")

Team
Atlanta Hawks             18671659.0
Boston Celtics            12000000.0
Brooklyn Nets             19689000.0
Charlotte Hornets         13500000.0
Chicago Bulls             20093064.0
Cleveland Cavaliers       22970500.0
Dallas Mavericks          16407500.0
Denver Nuggets            14000000.0
Detroit Pistons           16000000.0
Golden State Warriors     15501000.0
Houston Rockets           22359364.0
Indiana Pacers            17120106.0
Los Angeles Clippers      21468695.0
Los Angeles Lakers        25000000.0
Memphis Grizzlies         19688000.0
Miami Heat                22192730.0
Milwaukee Bucks           16407500.0
Minnesota Timberwolves    12700000.0
New Orleans Pelicans      15514031.0
New York Knicks           22875000.0
Oklahoma City Thunder     20158622.0
Orlando Magic             11250000.0
Philadelphia 76ers         6500000.0
Phoenix Suns              13500000.0
Portland Trail Blazers     8042895.0
Sacramento Kings          15851950.0
San Antonio Spurs         19689000.0
Toronto Raptors           13600000.0
Utah Jazz                 15409570.0
Washington Wizards        15851950.0
Name: Salary, dtype: float64

In [90]:
#Aggregations
#What is the average age of players? 
average_age = df["Age"].mean().round(2)
print(f"average_age: {average_age}")

#What is the maximum salary in the dataset? 
max_salary = df["Salary"].max()
print(f"max_salary: {max_salary}")

#What is the minimum weight? 
min_weight = df["Weight"].min()
print(f"min_weight: {min_weight}")

26.92
25000000.0
min_weight: 161.0

In [94]:
#Column Operations
#Create a new column Age_in_5_years. 
df["Age_in_5_years"] = df["Age"] + 5
print(df[["Age", "Age_in_5_years"]])
#Create a new column Salary_in_Millions (Salary / 1000000). 
df["Salary_in_Millions"] = df["Salary"] / 1000000
print(df[["Salary", "Salary_in_Millions"]])

      Age  Age_in_5_years
0    25.0            30.0
1    25.0            30.0
3    22.0            27.0
4    29.0            34.0
5    29.0            34.0
..    ...             ...
452  20.0            25.0
453  26.0            31.0
454  24.0            29.0
455  26.0            31.0
456  26.0            31.0

[446 rows x 2 columns]
         Salary  Salary_in_Millions
0     7730337.0            7.730337
1     6796117.0            6.796117
3     1148640.0            1.148640
4     5000000.0            5.000000
5    12000000.0           12.000000
..          ...                 ...
452   2239800.0            2.239800
453   2433333.0            2.433333
454    900000.0            0.900000
455   2900000.0            2.900000
456    947276.0            0.947276

[446 rows x 2 columns]

In [97]:
#Bonus 
#Which team has the highest total salary payout? 
highest_total_salary_per_team = df.groupby("Team")["Salary"].sum().max()
print(f"highest_total_salary_per_team: {highest_total_salary_per_team}")
team_highest_total_salary = df.groupby("Team")["Salary"].sum().idxmax()  #.idxmax() gives the name/index belonging to the highest value
print(f"team_highest_total_salary: {team_highest_total_salary}")
#Which position has the highest average salary?
highest_avg_salary_per_pos = df.groupby("Position")["Salary"].mean().round(2).max()
print(f"highest_avg_salary_per_pos: {highest_avg_salary_per_pos}")
pos_highest_avg_salary = df.groupby("Position")["Salary"].mean().idxmax()
print(f"pos_highest_avg_salary: {pos_highest_avg_salary}")

highest_total_salary_per_team: 106988689.0
team_highest_total_salary: Cleveland Cavaliers
highest_avg_salary_per_pos: 5967052.0
pos_highest_avg_salary: C

In [105]:
highest_avg_salary_per_pos = df.groupby("Position")["Salary"].mean().round(2).sort_values(ascending=False)
print(f"highest_avg_salary_per_pos: {highest_avg_salary_per_pos}")

highest_avg_salary_per_pos: Position
C     5967052.00
PG    5077829.22
SF    4857392.57
PF    4562482.99
SG    4009861.19
Name: Salary, dtype: float64

In [106]:
team_highest_total_salary = df.groupby("Team")["Salary"].sum().sort_values(ascending=False)
print(f"team_highest_total_salary: {team_highest_total_salary}")

team_highest_total_salary: Team
Cleveland Cavaliers       106988689.0
Los Angeles Clippers       94854640.0
Oklahoma City Thunder      93765298.0
Golden State Warriors      88868997.0
Chicago Bulls              86783378.0
San Antonio Spurs          84442733.0
New Orleans Pelicans       82750774.0
Miami Heat                 82515673.0
Charlotte Hornets          78340920.0
Memphis Grizzlies          76550880.0
Washington Wizards         76328636.0
Houston Rockets            75283021.0
New York Knicks            73303898.0
Atlanta Hawks              72902950.0
Los Angeles Lakers         71770431.0
Sacramento Kings           71683666.0
Dallas Mavericks           71198732.0
Toronto Raptors            71117611.0
Milwaukee Bucks            69603517.0
Detroit Pistons            67168263.0
Indiana Pacers             66751826.0
Phoenix Suns               63445135.0
Utah Jazz                  63060091.0
Orlando Magic              60161470.0
Denver Nuggets             60121930.0
Minnesota Timberwolves     59709697.0
Boston Celtics             58541068.0
Brooklyn Nets              52528475.0
Portland Trail Blazers     48301818.0
Philadelphia 76ers         30992894.0
Name: Salary, dtype: float64